name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Trigger the action on changes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js environment (if needed)
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust according to your app's Node.js version

    - name: Install Dependencies
      run: |
        npm install

    - name: Build the Project
      run: |
        npm run build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<your-app-service-name>'  # Azure App Service name
        slot-name: 'production'  # Change if using slots
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

